
<form action="<?php echo Mage::getUrl('adminMP/adminhtml_index/save') ?>" method="post">
  <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
  <fieldset>
    <ul>
      <li>
       <label for="nom">First name</label>
       <input type="text" id="nom" name="nom" />
      </li>
      <li>
         <label for="prenom ">Last name</label>
         <input type="text" id="prenom" name="prenom" />
      </li>
      <li>
        <label for="nom">Phone</label>
        <input type="text" id="telephone" name="telephone" />
      </li>
      <li>
        <input type="submit" value="Save" />
      </li>
    </ul>
 </fieldset>
</form>

<?php
echo $this->methodblock();
 ?>
