<form action="<?php echo Mage::getUrl('mailPerformance/index/save') ?>" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="id_magento">id magento</label>
       <input type="text" id="id_magento" name="id_magento" />
     </li>
     <li>
         <label for="id_mailPerf ">id mailPerf</label>
         <input type="text" id="id_mailPerf" name="id_mailPerf" />
     </li>
  </ul>
 </fieldset>
</form>

<?php
echo $this->methodblock();
 ?>
