<?php
?>
<table>
    <tr>
        <td>
			<button 
				style=""
                class="scalable" 
                onclick="javascript:window.location.replace(window.location.href+'../../../../../adminMP/adminhtml_index/csv');"
                id= "<?php echo $this->getHtmlId() ?>"
                type="button">
                <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
            </button>            
        </td>
    </tr>
</table>